model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    reg_weight: 1.0
    special_loss: null # One of (null, dreambooth, contrastive)
    #special_loss: contrastive
    #neg_weight: 0.02
    linear_start: 0.00085
    linear_end: 0.0120
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    training_mode: main # One of (full, main, cond, dfit, attention, spec)
    dfit_train_cond: false # DiffFit
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    embedding_reg_weight: 0.0
    noise_learned_conditioning: false # experimental
    input_perturbation_scale: 0.1 # experimental
    noise_offset_scale: 0 # experimental
    #max_train_timestep: 650 # experimental

    personalization_config:
      target: ldm.modules.embedding_manager.EmbeddingManager
      params:
        placeholder_strings: ["*"]
        initializer_words: ["sculpture"]
        #per_image_tokens: false
        num_vectors_per_token: 1
        progressive_words: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        dropout: 0.15 # note!
        attn_dropout: 0.0 # experimental
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: true
        disable_flash_attn: true # DiffFit
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True # should be True if main_stage_trainable is True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    #cond_stage_config: __is_unconditional__

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
      #params:
        #version: laion/CLIP-ViT-L-14-laion2B-s32B-b82K # experimental

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    wrap: false
    train:
      target: ldm.data.personalized.ConcatPersonalizedBase
      params:
        size: 512
        set: train
        repeats: 1
        add_flipped_frac: 0.75
        add_sharpened_frac: 0.0
        add_autocontrast_frac: 0.15
        add_center_crop_frac: 0.85
        add_rand_rotation_frac: 0.0
        interpolation: lanczos
        crop_type: random
        shuffle: true
        use_caption_file: true  # Set to false if training a Dreambooth model

    reg:
      target: ldm.data.personalized.ConcatPersonalizedBase
      params:
        size: 512
        set: train
        reg: true
        random_selection: true
        #per_image_tokens: false
        repeats: 1000
        interpolation: lanczos
        crop_type: center
        shuffle: true

    validation:
      target: ldm.data.personalized.ConcatPersonalizedBase
      params:
        size: 512
        set: val
        #per_image_tokens: false
        repeats: 1
        interpolation: lanczos
        crop_type: center
        shuffle: false
        use_caption_file: true  # Set to false if training a Dreambooth model

lightning:
  modelcheckpoint:
    params:
      every_n_epochs: 3
  callbacks:
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        every_n_epochs: 2  # note! requires a lot of disk space
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 150 # note!
        max_images_seeded: 2
        max_images: 2
        increase_log_steps: False
        log_images_kwargs:
          ddim_steps: 35
          sampler: dpmpp_2m
          unconditional_guidance_scale: 7.5
          #sampler: dpmpp_2m

  trainer:
    benchmark: True
    max_steps: 100000
    accumulate_grad_batches: 1 # note!
    log_every_n_steps: 25
    accelerator: gpu
    devices: 0,
